# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CartaoDeVisitasIOS6' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MBProgressHUD', '~> 1.1.0'
  pod 'Firebase/Auth'


end


